// Generated by Bisonc++ V4.13.01 on Sun, 08 Jan 2017 20:16:38 +0300

#ifndef Parser_h_included
#define Parser_h_included

// $insert baseclass
#include "parserbase.h"
// $insert scanner.h
#include "../scanner/scanner.h"


#undef Parser
class Parser: public ParserBase
{
    // $insert scannerobject
    Scanner d_scanner;
    std::shared_ptr<Node> _ast;
        
    public:
        // NOTE: this ctor is written by hand
        Parser(std::istream &in, std::ostream &out);
        int parse();
        std::shared_ptr<Node> ast();

    private:
        void error(char const *msg);    // called on (syntax) errors
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc

    // support functions for parse():
        void executeAction(int ruleNr);
        void errorRecovery();
        int lookup(bool recovery);
        void nextToken();
        void print__();
        void exceptionHandler__(std::exception const &exc);
};


#endif
